### ISSUE TITLE
Lemma 17.10 (-1)^|S| missing.

### ISSUE THREAD

**Issue by Narfinger** [dasarpmar/lowerbounds-survey#12]
The bug is in the title unless I am missing something.

**Comment by dasarpmar** [comment]
I am assuming you are referring to Ryser's formula. I don't think there is a 1/|S| in the statement. 
2!. x1x2 = (x_1 + x_2)^2 - x_1^2 - x_2^2

**Comment by Narfinger** [comment]
Sorry, I misstyped the first time I submitted the bug. The fix should include a (-1)^|S|.

**Comment by dasarpmar** [comment]
Ah yes. I've fixed that in 4440559. Thanks. Will soon post an updated release.
